### ISSUE TITLE
SPeL fails to instantiate java.util.Date

### ISSUE THREAD

**Issue by igorbga** [verronpro/docx-stamper#220]
**Describe the bug**
when you try to instantiate a date in the document it fails.

**To Reproduce**
1. Create a docx template that merely has: ${new java.util.Date()}
2. Run it through the stamper

**Expected behavior**
A new docx should have been generated showing the current date  in format "dd.MM.yyyy"

**Actual behaviour**
The rendering of the new docx fails with this message:

```
org.springframework.expression.spel.SpelEvaluationException: EL1002E: Constructor call: No suitable constructor found on type java.util.Date for arguments ()
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java version: 17
 - docx4j version: 11.4.9
 - docx-stamper version 1.6.5

**Additional context**
I attach a file
[date.docx](https://github.com/verronpro/docx-stamper/files/13442235/date.docx)

**Comment by dallanmc** [comment]
How are you instantiating the DocxStamper class? Can you show us in code?

**Comment by igorbga** [comment]
Is in a Spring Boot controller and looks like this:

```java
	@PostMapping("/render")
	public ResponseEntity<StreamingResponseBody> render(@RequestParam MultipartFile template,
			@RequestParam("model") JsonNode json) throws IOException {

		DocxStamper<Model> stamper = new DocxStamper<>(
				new DocxStamperConfiguration());

		InputStream templateIs = template.getInputStream();
		String templateName = template.getOriginalFilename();
		var extension = FilenameUtils.getExtension(templateName).toLowerCase();
		var mediaType = SUPPORTED_EXTENSION_TO_MEDIATE_TYPE.get(extension);
		if (mediaType == null) {
			throw new IllegalArgumentException("Template with unsupported extension: " + extension);
		}
		Model model = new Model(json);
		StreamingResponseBody stream = out -> {
			stamper.stamp(templateIs, model, out);
		};
		return ResponseEntity.ok()
				.contentType(mediaType)
				.body(stream);
	}
```

The "Model" class itself shouldn't be very relevant for this issue because the provided template is not using anything from the model but just in case you need more context here is what I'm trying to achieve and you can see the Model class there:

https://github.com/thombergs/docx-stamper/issues/131

Unlike in the original DOCX-stamper in your fork my Model seems to work properly, but then i found the Date instantiation issue.

**Comment by igorbga** [comment]
Just to make sure that this is not something related to my Context or the fact that I'm using Spring Boot I made the most minimalistic project I could think of to reproduce the issue:

[demo.zip](https://github.com/verronpro/docx-stamper/files/13447480/demo.zip)

The command line programa expects 2 arguments, the path to the template and the path to the output.

You should be able to reproduce the issue just by executing this project.

Just in case it helps to shed some light this expression doesn't work either:

```
${T(java.time.LocalDateTime).now()}
```

Might it have something to do with SPeL's TypeLocator?

**Comment by dallanmc** [comment]
I think I've spotted the commit that changed this: 
https://github.com/verronpro/docx-stamper/commit/2f801b1ad9a5ea1f5d634f91fd0ee9f5dbd37c60

Docxstamper moved from `NoOpEvaluationContextConfigurer` to a new `DefaultEvaluationContextConfigurer`. 

In the `DefaultEvaluationContextConfigurer` I can see this on line 24: 

`context.setConstructorResolvers(Collections.emptyList());`

What happens then in the StandardEvaluationContext is this: 

```
	private List<ConstructorResolver> initConstructorResolvers() {
		List<ConstructorResolver> resolvers = this.constructorResolvers;
		if (resolvers == null) {
			resolvers = new ArrayList<>(1);
			resolvers.add(new ReflectiveConstructorResolver());
			this.constructorResolvers = resolvers;
		}
		return resolvers;
	}
```
Because our resolvers is an empty list instead null, the ReflectiveConstructorResolver (which will resolve the java.util.Date) is no longer added. 

The simplest fix I can see for this, is to remove line 24 from the `DefaultEvaluationContextConfigurer` or explicitly set the resolvers to null `context.setConstructorResolvers(null);`

in the meantime @igorbga , version 1.6.5 doesn't work (as you know), but 1.6.4 works for your use case (just tested).

**Comment by igorbga** [comment]
Thanks @dallanmc, glad to know that you could spot the issue.

I worked around it by implementing some custom functions for date management that allow me to format the dates in the template itself so right now I can still work with versin 1.6.5 . Nevertheless not being able to instantiate Java classes might be a quite limiting factor so I might try your suggestion.

Just for informative purpose, is releasing a 1.6.6 in the near future in your plans ?

Thanks

**Comment by dallanmc** [comment]
I am not involved in the docxstamper project, so I'm not sure about release dates or anything.

**Comment by caring-coder** [comment]
Hi everyone, sorry, real life caught up to me the last few months.

I confirm i changed the default setting for security reasons. For example, by default the template could looks like this: 
[SpelInjectionTest.docx](https://github.com/verronpro/docx-stamper/files/14123810/SpelInjectionTest.docx)
Allowing the default settings to to be way to easy to break an app server JVM.

You should probably still be able to use the previous template if you do the setup thusly:
```java
new DocxStamperConfiguration()
    .setEvaluationContextConfigurer(new NoOpEvaluationContextConfigurer())
```

I'll reopen the issue, in order to have a trace of the work left to have ths feature easy to show in an API. The current fix is mostly a workaround, because the legacy implementation API bind a lot of things early in the constructors, and my goal is to have a 1.7.0 version with an API allowing me to have 'just in time' objects constructions, type resolutions, and context solving.

**Comment by caring-coder** [comment]
I'll take you example to have better examples of use cases in my test though, thanks

**Comment by caring-coder** [comment]
Hello @igorbga, @dallanmc 
I'm taking some time to look more thoroughly at your issue and i identify several use case:

- the ability to create new java object instances directly in the template ${new java.util.Date()}
- the ability to call static method of java classes like in ${T(java.time.LocalDateTime).now()}
- i also imagine the case of defineing different concurring date & time formatting on various entry in the same template

Are those use case that you feel should be better addressed ? Like by giving some preset, or some configuration method that would clearly explain how to add some authorized types to the EvaluationContext ?

PS:
For information, i do believe that keeping the power to evaluate the full Spel language (like in version prior to 1.6.5) is still useful, and we will keep supporting this case. Especially when the templates are not sent directly by end-user, and can be read-proofed before any stamping tentative in a production environment.
We just don't want the default being set up with that much attack surface.

**Comment by caring-coder** [comment]
Close since traced the answer i want to give this issue in #411
