### ISSUE TITLE
Notes on displayParagraphIf / displayTableColumnIf affected by resolution order

### ISSUE THREAD

**Issue by mpressmar** [verronpro/docx-stamper#513]
**Describe the bug**
Less than a bug, I only want to document some findings I made, templates which broke starting from version 2.3.0.

(1) Some of our templates are using a displayParagraphIf comment which spans multiple table cells. This worked well in version 2.2.0, but since 2.3.0 it will result in an error.

(2) We're using a custom displayTableColumnIf comment processor which is based very closely on the provided displayTableRowIf processor: it removes all cells of the respective column in the table. We are applying the displayTableColumnIf in the header of the very last column of the table in combination with a repeatTableRow processor covering the entire body row.
In version 2.2.0 of officestamper this combination worked well, while since version 2.3.0 it broke: The repeatTableRow's comment end cannot be found, and the repeatTableRow is therefore ignored. 
My understanding: In version 2.2.0 first all comments for the document were collected, and afterwards they were processed. In version 2.3.0 this changed, the displayTableColumnIf is committed, removing the cell in which the comment end of the repeatTableRow is placed.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Java version: 21
 - docx4j version: 11.5.0
 - docx-stamper version 2.3.0 until 2.5.0

**Additional context**
After a significant time to debug these failures I understand that conceptually the way officestamper iterates through comments has changed with 2.3.0. What I considered initially bugs is just a different behavior, and I have my doubts that the library is intended to support the two use cases above.

Our resolution is to adapt the templates instead:
Re (1): we can replace it with displayTableRowIf resp. several displayParagraphIf comments.
Re (2): we can move the displayTableColumnIf comment from the header row into the body row in which the repeatTableRow is located; in this way we can ensure the right order of comment processing.

**Comment by caring-coder** [comment]
First, I'm sorry if I broke your templates, I really didn't know that the processor supporting this kind of use case.
Second, Yes the behaviour changed greatly. The goal in the future is to be able to process the document in a stream, instead of loading it completely in memory, so the gradual changes in comment processors behaviour you noticed.
For the issue (1), would a dedicated displayCellsIf() processor be sufficient ? And if yes, do you think it should be able to span several rows in a table ?
For the issue (2), actually the displayTableRow and repeatTableRow comments do not need to span the whole row to function correctly. You can make a comment in a cell you know won't disappear and your setup should work fine.

Do not hesitate to comment further, I can take some time to assist with your issues.
